[project]
name = "neoparatranz"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "lxml>=6.0.0",
    "typer>=0.16.0",
    "typing>=3.10.0.0",
]

