[project]
name = "neoparatranz"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "lxml>=6.0.0",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.11",
]

